# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://damon-murdoch.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Damon Murdoch
# Description of the Site
description: Software Developer and Competitive Pokemon Player
# URL of Image of the Site
site-image: /assets/images/bg.jpg
# Keywords of the Site
site-keywords: Profile
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/bg.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: damon.j.murdoch@gmail.com
facebook_username: SirScrubbs
twitter_username: SirScrubbington
instagram_username: sirscrubbington
linkedin_username: damon-murdoch
github_username:  damon-murdoch
youtube_channel_id: UCQGOvCJaUVBQxpHBExbx8_Q
reddit_username: SirScrubbs
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
#google-analytics: UA-163806439-1

# Disqus
#disqus-shortname: thedevslot

# Name of the Author
author-name: Damon Murdoch
# URL for the Image of the Author
author-image: /assets/images/pfp.jpg # https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: Hi! I'm Damon Murdoch, a Software Developer and Competitive Pokemon player from Queensland, Australia. My skills primarily involve scripting, back-end development and web programming to develop applications in Python, PHP and Powershell. As far as Pokemon goes, I am one of the most recognised players in Queensland in terms of performances and have also created a number of resources such as tools and articles for the community.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/damon-murdoch

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
